### ISSUE TITLE
sosa:hasMember from tern:ObservationCollection not compatible with rdflib

### ISSUE THREAD

**Issue by miekeGR** [ternaustralia/ontology_tern#157]
Greetings :-D 

We are trying to use the tern:ObservationCollection to capture information about the NSL name match results to a scientificName; however, rdflib is rejecting sosa:hasMember as a term. I was looking at the sosa documentation (https://www.w3.org/TR/vocab-ssn/#overview-of-classes-and-properties) and found a diagram in section 6.4.2 that aligns sosa:Observation with oboe:Measurement and OBOE has oboe:ObservationCollection with "hasMember" and was wondering should we use "oboe:hasMember" instead of "sosa:hasMember" as the predicate to link Observation objects to the ObservationCollection?

Thanks

**Comment by miekeGR** [comment]
Cheers, thanks for that @edmondchuc It wasn't me, I was raising it on behalf of one of our team members. I'll ask him to join the conversation.

**Comment by HaydenGaia** [comment]
Hi @edmondchuc 

I'll confess firstly that I'm new to Linked Data and RDF, so I may be missing some key concepts or information.

The issue was first brought to my attention when using `sosa:hasMember` with `rdflib`. As it is not explicitly defined on the declarative `SOSA` namespace, `rdflib` warns the user:
```python
>>> import rdflib
>>> rdflib.__version__
'6.1.1'
>>> rdflib.SOSA
Namespace("http://www.w3.org/ns/sosa/")
>>> rdflib.SOSA.hasMember
<stdin>:1: UserWarning: Code: hasMember is not defined in namespace SOSA
rdflib.term.URIRef('http://www.w3.org/ns/sosa/hasMember')
```

I understand it is still useable (i.e., just a warning), but it raised the following questions for me:
  * is `sosa:hasMember` the correct predicate, does it exist?
  * if so, why is it not in the `rdflib.SOSA` namespace
  * also, why does it not appear in the `.ttl` ontology at: http://www.w3.org/ns/sosa/

Thanks!

**Comment by edmondchuc** [comment]
Hi @HaydenGaia, both `sosa:ObservationCollection` and `sosa:hasMember` are defined by the SSN extensions work. See https://www.w3.org/TR/vocab-ssn-ext/. You will likely get the same error if you try to do
```python
>>> import rdflib
>>> rdflib.SOSA.ObservationCollection
```
Recently rdflib introduced the `DefinedNamespace` class, which `SOSA` is a subclass of. See https://github.com/RDFLib/rdflib/blob/master/rdflib/namespace/_SOSA.py. By default, it will warn you if you try to access a property which does not exist in the namespace.

Since `SOSA` is a class, you can simply extend it and create your version of `SOSA` with the additional properties defined in SSN extension.

```python
from rdflib import SOSA as RDFLibSOSA, URIRef


class SOSA(RDFLibSOSA):
    ObservationCollection: URIRef
    
    hasMember: URIRef


print(SOSA.hasMember)
print(SOSA.ObservationCollection)

```

Output:
```
http://www.w3.org/ns/sosa/hasMember
http://www.w3.org/ns/sosa/ObservationCollection
```

**Comment by HaydenGaia** [comment]
> `sosa:ObservationCollection` and `sosa:hasMember` are defined by the SSN extensions work. See https://www.w3.org/TR/vocab-ssn-ext/.

Ah, I see.
I didn't really understand how the SSN extensions work functioned. I assumed it would have to use a different prefix/url (i.e. not `sosa` / `http://www.w3.org/ns/sosa/`) or it would have to refer to `https://www.w3.org/TR/vocab-ssn-ext/` in some way.

But, if the subclass method above is valid, then I am more than happy with that.

Thanks for the help! Feel free to close.

**Comment by miekeGR** [comment]
Thanks for that info @edmondchuc :-D
