### ISSUE TITLE
Over/Under specification of temporal values

### ISSUE THREAD

**Issue by nicholascar** [ternaustralia/ontology_tern#58]
A `tern:Observation` _MUST_ have:

* exactly 1 `sosa:resultTime` property indicating a `xsd:dateTime` literal value
* exactly 1 `sosa:phenomenonTime` property indicating a `tern:Instant`

The `sosa:resultTime` is ok - literal dateTime(Stamp) value (see Issue $57) - but `sosa:phenomenonTime` is either over- or under-specified.

For `sosa:phenomenonTime`, a complex object, an instance of `tern:Instant`, is required as the range value but then that instance is itself required to have exactly 1 `time:inXSDDateTimeStamp` property with a literal value. What then is the purpose of requiring a complex object if it's always locked to a literal in that way? Why not just have:

* exactly 1 `sosa:resultTime` property indicating a `xsd:dateTime` literal value
* exactly 1 `sosa:phenomenonTime` property indicating a `xsd:dateTime` literal value

If the purpose of requiring an instance of `tern:Instant` is to allow for multiple ways of indicating temporarily, the `tern:Instant` property restriction should be removed. If a `xsd:dateTime(Stamp)` literal value is required, why the `tern:Instant`?

**Comment by edmondchuc** [comment]
I agree. I would prefer to have a literal value for `sosa:phenomenonTime`(since most survey data only provide time `Instants` for observations. The `Instant` constraint currently in place is to meet the `sosa:phenomenonTime`'s definition that its values are a `time:TemporalEntity`, which `time:Instant` and `time:Interval` are subclasses.

I was planning to add `Interval` once we come across some datasets with time intervals, but I think to be complete, we should add it now with the proper constraints. 

Proposal:
- Still use a complex value to be interoperable with SOSA (since it expects a `time:TemporalEntity`)
- `tern:Instant`must have 1 value with one of:
    - `time:inXSDDate`
    - `time:inXSDDateTimeStamp`
    - `time:inXSDgYear`
    - `time:inXSDgYearMonth`
    - `time:inTimePosition`
    - `time:inDateTime`
- `tern:Interval` - a minimal valid `Interval` - see https://www.w3.org/TR/vocab-ssn/#b-3-apartment-134 example
- An `Observation`'s `sosa:phenomenonTime` can be either an `Instant` or an `Interval`.



Related: relax/improve constraints https://github.com/ternaustralia/ontology_tern/issues/63

**Comment by dr-shorthair** [comment]
In general OWL is not so happy with literals, and extremely unhappy with either/ors (`rdf:Resource`). 
You generally see a pattern like https://www.w3.org/TR/vocab-ssn/#SOSAhasResult vs. https://www.w3.org/TR/vocab-ssn/#SOSAhasSimpleResult but we didn't do that with the temporal properties - note that https://www.w3.org/TR/vocab-ssn/#SOSAresultTime has a literal value, while https://www.w3.org/TR/vocab-ssn/#SOSAphenomenonTime has an object value
