### ISSUE TITLE
Site's transitively-required sosa:isResultOf is problematic

### ISSUE THREAD

**Issue by nicholascar** [ternaustralia/ontology_tern#85]
`Site` is a subclass of `Sample` which is a subclass of `Result`.

`Result` must have exactly one `sosa:isResultOf` property.

This is ontologically correct but difficult to work with: what is a sensible `sosa:isResultOf` for a permanent monitoring station, or even a temporary survey site? 

The only `sosa:isResultOf` object allowances are `Observation`, `Sampling` or `Attribute` and the last seems odly-placed compared to the first two: the first two are temporal events, the last is something very different: an property of something else.

So what would make a sensible object value for a `Sites`'s `sosa:isResultOf` property? `Sampling` events may be carried out with the `Site` as the FoI but I don't think the `Site` is a result of those `Sampling` instances. Is the `Site` established as a result of an `Observation`? Of what? An ultimate FoI perhaps that isn't a site itself? `Attribute` seems irrelevant unless the `Site` is a result of an `Attribute` of an ultimate FoI, but this seems very difficult...

**Comment by dr-shorthair** [comment]
A site is the result of a site-establishment act. 
A site is established because it is representative (in some way, possibly just because it is conveniently visitable) of some geography. 
An ecological monitoring site should be sampling some environmental region or ecosystem, or similar.

**Comment by nicholascar** [comment]
An example of a “a site-establishment act” please!

I understand the theory but what I don’t have is a sensible example of a`Sampling`, `Observation` or an `Attribute` that created one. 

The SHACL says it has to be one of this things only, not a generic “make site” `prov:Activity` or similar.

**Comment by miekeGR** [comment]
I agree with Nick, the site-establishment act seems redundant and makes creating a site more complicated. I can't work out how to get around it without making up some dummy data or resorting to Sampling e.g. Australia haha.

**Comment by dr-shorthair** [comment]
- For a site that is visited once, the site-visit establishes the site. 
- If that site is visited again, then it is the first site visit that established it
- for a site that is established so that it is permanently occupied, there will have been a significant process to achieve that, with selection criteria, permissions, all sorts. It may not have been well recorded, but it definitely occurred. 

This is not hard to understand, surely? 
Of course RDFS/OWL does not require that the site-establishment-act is actually instantiated with lots of metadata etc. 
But _logically_ a site is the result of an act of site establishment, so that is why it has been modeled as a specialization of Sample, with the site-establishment a special kind of Sampling.

**Comment by dr-shorthair** [comment]
@miekeGR it might be the case that _describing_ the site-establishment act is not new information. It will often just be the initial site-visit. In a graph representation, the same node (URI) can have many connections, playing more than one role, and have more than one `rdf:type`. That just means that it is a member of more than one set. This is not object-orientation, it is FOL.

**Comment by nicholascar** [comment]
> For a site that is visited once, the site-visit establishes the site.

Then you will have to alter the ontology's SHACL as a `SiteVisit` is a `prov:Activity` but not a `tern:Observation`, `tern:Sampling` or a `tern:Attribute`.

You just said that a `tern:SiteVisit` *may also be* a `tern:Observation` (multiple types) but there is no obvious way to infer that the establishment act is both of those things and given that there's no ontology rule to infer that a SiteVisit is an Observation, SHACL validation will fail unless it's specifically indicated that it is.

Sure, we can indicate anything's anything (multiple types) in data but this doesn't seem expected here: both an Observation and a SiteVisit just to pass validation.

I suggest you just generalise the SHACL lock on `sosa:isResultOf` to `prov:Activity`, or you make `tern:SiteVisit` a subclass of `tern:Observation`.

**Comment by dr-shorthair** [comment]
I haven't worked on the SHACL, so someone else will have to fix that. 

However, I would expect `sosa:Observation` and `sosa:Sampling` to both be sub-classes of `prov:Activity` so subsumption should allow for this case already?

**Comment by nicholascar** [comment]
> I would expect `sosa:Observation` and `sosa:Sampling` to both be sub-classes of `prov:Activity`...

They are.

> ...so subsumption should allow for this case already?

Yes, so either of the two options I suggest are easily implementable. SHACL will see that the SiteVisit is an Activity - so adding Activity works (and makes listing subclasses of Activity redundant) - and SiteVisit _could_ be thought of as a special Observation easily enough, so that too would work.

Currently though, the ontology just doesn't present the hierarchies SHACL needs.

The de-coupling of the OWL and SHACL should probably be the vehicle to fix this: no need for the SHACL requirements to match the OWL class hierarchy directly.

**Comment by dr-shorthair** [comment]
@edmondchuc can you fix the SHACL?

**Comment by edmondchuc** [comment]
@dr-shorthair I'm going to start on the ontology/SHACL issues tomorrow and put the cookbook content on pause for a bit.

**Comment by edmondchuc** [comment]
Hi all, I am trying to follow the conversation here to see what needs to be done. 

Summary of my understanding:
- A `Site` is the result of a site-establishment-act represented as a `Sampling`. See [example](https://github.com/ternaustralia/bdr-ibsa-sample-data/blob/master/output.ttl#L201-L208).
- A `Site` can have one or more `SiteVisit` instances. A `SiteVisit` is an activity.
- A `Site` can have one or more `Observation` or `Sampling` activities occur in the context of a `SiteVisit`. Think of `Observation` and `Sampling` as sub-activities that happen during a `SiteVisit`. 

@nicholascar can you point me to where you are seeing
> The only `sosa:isResultOf` object allowances are `Observation`, `Sampling` or `Attribute`

I cannot see where `sosa:isResultOf` allows `Attribute` and there were no changes to `sosa:isResultOf` in the last couple of months (I think). I do remember at some point last year this was there but it should have been removed due to https://github.com/ternaustralia/ontology_tern/issues/12. Is it possible you are looking at an older version of the SHACL?

The current SHACL for [Site](https://linkeddata.tern.org.au/viewers/tern-ontology?uri=https://w3id.org/tern/ontologies/tern/Site) is constrained by its superclass `Sample` and its definition for `sosa:isResultOf` requires at least one IRI value that is an instance of `Sampling`. 

---

> So what would make a sensible object value for a Sites's sosa:isResultOf property?

It should always be a `Sampling`. See [example](https://github.com/ternaustralia/bdr-ibsa-sample-data/blob/master/output.ttl#L201-L208). 

Let me know if this clears things up and please advise me if I've missed anything or if anything needs to be modified in the ontology/SHACL.

**Comment by miekeGR** [comment]
Hi @edmondchuc I can confirm, before the rebranding of the site (from green to orange), Attribute was listed as an option for the sosa:isResultOf on https://linkeddata-dev.tern.org.au/viewers/tern-ontology?uri=https://w3id.org/tern/ontologies/tern/Site 

But now I only see Observation and Sampling.

**Comment by nicholascar** [comment]
> @nicholascar can you point me to where you are seeing

>> The only sosa:isResultOf object allowances are Observation, Sampling or Attribute

It was within the last table row on the page https://w3id.org/tern/ontologies/tern/Site but it looks like Attribute is now gone! @miekeGR has beaten me to it!

**Comment by nicholascar** [comment]
So, in answer to the fundamental question in this issue:

TERN `Site` instances do need to be indicated as having been created by a `tern:Sampling` event with the `sosa:isResultOf` property and that site establishment sampling is of the `tern:FeatureOfInterest` indicated on the `Sampling` instance with a `sosa:hasFeatureOfInterest` property.

See example https://github.com/ternaustralia/bdr-ibsa-sample-data/blob/master/output.ttl#L201-L208.

**Comment by edmondchuc** [comment]
Thanks @nicholascar and @miekeGR and sorry for the confusion.
